#ifndef INCLUDE_CONFIG_H
#define INCLUDE_CONFIG_H

#define PROJECT_NAME "wumpus"
#define PROJECT_VER  "0.6.2"
#define PROJECT_VER_MAJOR 0
#define PROJECT_VER_MINOR 6
#define PTOJECT_VER_PATCH 2

#endif // INCLUDE_CONFIG_H
